package session

import (
	"crypto/rand"
	"fmt"
	rnd "math/rand"
	"net/http"
	"time"

	"github.com/oklog/ulid"

	"github.com/gridanias-helden/voidsent/pkg/models"
	"github.com/gridanias-helden/voidsent/pkg/storage"
)

var names = []string{
	"Albatross", "Alligator", "Alpaca", "Ape",
	"Bat", "Bear", "Bee", "Butterfly",
	"Camel", "Cat", "Chicken", "Cow",
	"Dog", "Dolphin", "Donkey", "Duck",
	"Eagle", "Elephant", "Elk", "Emu",
	"Falcon", "Ferret", "Fish", "Fox",
	"Gecko", "Gnat", "Goat", "Gorilla",
	"Hamster", "Hawk", "Hornet", "Horse",
	"Ibex", "Ibis", "Iguana", "Impala",
	"Jaguar", "Jay", "Jellyfish", "Junglefowl",
	"Kagaroo", "Kingbird", "Kite", "Koala",
	"Ladybug", "Lemur", "Leopard", "Lobster",
	"Mammoth", "Mantis", "Meerkat", "Mouse",
	"Narwhal", "Newt", "Nightingale",
	"Okapi", "Opossom", "Otter", "Owl",
	"Panther", "Panda", "Penguim", "Pony",
	"Rabbit", "Raccoon", "Raven", "Rook",
	"Salamander", "Shark", "Sheep", "Squirrel",
	"Tapir", "Tiger", "Toad", "Turtle",
	"Viper",
	"Wasp", "Weasel", "Whale", "Wolf",
	"Zebra",
}

var adjectives = []string{
	"Adorable",
	"Adventurous",
	"Aggressive",
	"Agreeable",
	"Alert",
	"Alive",
	"Amused",
	"Angry",
	"Annoyed",
	"Annoying",
	"Anxious",
	"Arrogant",
	"Ashamed",
	"Attractive",
	"Average",
	"Awful",
	"Bad",
	"Beautiful",
	"Better",
	"Bewildered",
	"Black",
	"Bloody",
	"Blue",
	"Blue-eyed",
	"Blushing",
	"Bored",
	"Brainy",
	"Brave",
	"Breakable",
	"Bright",
	"Busy",
	"Calm",
	"Careful",
	"Cautious",
	"Charming",
	"Cheerful",
	"Clean",
	"Clear",
	"Clever",
	"Cloudy",
	"Clumsy",
	"Colorful",
	"Combative",
	"Comfortable",
	"Concerned",
	"Condemned",
	"Confused",
	"Cooperative",
	"Courageous",
	"Crazy",
	"Creepy",
	"Crowded",
	"Cruel",
	"Curious",
	"Cute",
	"Dangerous",
	"Dark",
	"Dead",
	"Defeated",
	"Defiant",
	"Delightful",
	"Depressed",
	"Determined",
	"Different",
	"Difficult",
	"Disgusted",
	"Distinct",
	"Disturbed",
	"Dizzy",
	"Doubtful",
	"Drab",
	"Dull",
	"Eager",
	"Easy",
	"Elated",
	"Elegant",
	"Embarrassed",
	"Enchanting",
	"Encouraging",
	"Energetic",
	"Enthusiastic",
	"Envious",
	"Evil",
	"Excited",
	"Expensive",
	"Exuberant",
	"Fair",
	"Faithful",
	"Famous",
	"Fancy",
	"Fantastic",
	"Fierce",
	"Filthy",
	"Fine",
	"Foolish",
	"Fragile",
	"Frail",
	"Frantic",
	"Friendly",
	"Frightened",
	"Funny",
	"Gentle",
	"Gifted",
	"Glamorous",
	"Gleaming",
	"Glorious",
	"Good",
	"Gorgeous",
	"Graceful",
	"Grieving",
	"Grotesque",
	"Grumpy",
	"Handsome",
	"Happy",
	"Healthy",
	"Helpful",
	"Helpless",
	"Hilarious",
	"Homeless",
	"Homely",
	"Horrible",
	"Hungry",
	"Hurt",
	"Ill",
	"Important",
	"Impossible",
	"Inexpensive",
	"Innocent",
	"Inquisitive",
	"Itchy",
	"Jealous",
	"Jittery",
	"Jolly",
	"Joyous",
	"Kind",
	"Lazy",
	"Light",
	"Lively",
	"Lonely",
	"Long",
	"Lovely",
	"Lucky",
	"Magnificent",
	"Misty",
	"Modern",
	"Motionless",
	"Muddy",
	"Mushy",
	"Mysterious",
	"Nasty",
	"Naughty",
	"Nervous",
	"Nice",
	"Nutty",
	"Obedient",
	"Obnoxious",
	"Odd",
	"Old-fashioned",
	"Open",
	"Outrageous",
	"Outstanding",
	"Panicky",
	"Perfect",
	"Plain",
	"Pleasant",
	"Poised",
	"Poor",
	"Powerful",
	"Precious",
	"Prickly",
	"Proud",
	"Putrid",
	"Puzzled",
	"Quaint",
	"Real",
	"Relieved",
	"Repulsive",
	"Rich",
	"Scary",
	"Selfish",
	"Shiny",
	"Shy",
	"Silly",
	"Sleepy",
	"Smiling",
	"Smoggy",
	"Sore",
	"Sparkling",
	"Splendid",
	"Spotless",
	"Stormy",
	"Strange",
	"Stupid",
	"Successful",
	"Super",
	"Talented",
	"Tame",
	"Tasty",
	"Tender",
	"Tense",
	"Terrible",
	"Thankful",
	"Thoughtful",
	"Thoughtless",
	"Tired",
	"Tough",
	"Troubled",
	"Ugliest",
	"Ugly",
	"Uninterested",
	"Unsightly",
	"Unusual",
	"Upset",
	"Uptight",
	"Vast",
	"Victorious",
	"Vivacious",
	"Wandering",
	"Weary",
	"Wicked",
	"Wide-eyed",
	"Wild",
	"Witty",
	"Worried",
	"Worrisome",
	"Wrong",
	"Zany",
	"Zealous",
}

type GuestLogin struct {
	Sessions storage.Sessions
}

func GuestAvatar() string {
	return fmt.Sprintf("/assets/images/avatars/con%d.png", rnd.Intn(42)+1)
}

func (gl *GuestLogin) Register(w http.ResponseWriter, r *http.Request) {
	adjIndex := rnd.Intn(len(adjectives))
	nameIndex := rnd.Intn(len(names))
	playerName := fmt.Sprintf("%s%s", adjectives[adjIndex], names[nameIndex])

	sess := models.Session{
		ID:       ulid.MustNew(ulid.Now(), rand.Reader).String(),
		PlayerID: "guest:" + playerName,
		Username: playerName,
		Avatar:   GuestAvatar(),
		Updated:  time.Now().UTC(),
	}

	gl.Sessions.SaveSession(r.Context(), sess)

	sessionCookie := http.Cookie{
		Name:     "voidsent_session",
		Value:    sess.ID,
		Path:     "/",
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteDefaultMode,
	}

	http.SetCookie(w, &sessionCookie)
	http.Redirect(w, r, "/", http.StatusTemporaryRedirect)
}
