package session

import (
	rnd "math/rand"
	"strings"
)

var adjectivesDE = []string{
	"Aggressiv",
	"Ängstlich",
	"Anmutig",
	"Ärgerlich",
	"Aufgeregt",
	"Aufmerksam",
	"Begeistert",
	"Bekümmert",
	"Bewundernswert",
	"Blass",
	"Blau",
	"Blauäugig",
	"Blaugrün",
	"Bloß",
	"Brav",
	"Dankbar",
	"Dunkel",
	"Durstig",
	"Edel",
	"Ehrlich",
	"Eifrig",
	"Einfach",
	"Eklig",
	"Elegant",
	"Empört",
	"Entschlossen",
	"Erstaunlich",
	"Erwartungsvoll",
	"Fabelhaft",
	"Fantastisch",
	"Faul",
	"Feindlich",
	"Fröhlich",
	"Frustriert",
	"Fürchterlich",
	"Gedankenlos",
	"Gelangweilt",
	"Gemein",
	"Genial",
	"Gereizt",
	"Geschäftig",
	"Gesellig",
	"Gespannt",
	"Gierig",
	"Glamourös",
	"Glücklich",
	"Goldig",
	"Grau",
	"Grotesk",
	"Grün",
	"Gut",
	"Hässlich",
	"Herzlos",
	"Hilflos",
	"Himmelblau",
	"Hoffnungsvoll",
	"Höflich",
	"Hübsch",
	"Humorvoll",
	"Hungrig",
	"Interessiert",
	"Jovial",
	"Kahl",
	"Kalt",
	"Keck",
	"Klug",
	"Komisch",
	"Krank",
	"Kreativ",
	"Kühn",
	"Langweilig",
	"Laut",
	"Lebendig",
	"Leer",
	"Liebenswert",
	"Lila",
	"Lustig",
	"Melancholisch",
	"Mutig",
	"Mysteriös",
	"Nervös",
	"Niedlich",
	"Opulent",
	"Panisch",
	"Perfekt",
	"Persönlich",
	"Pink",
	"Prächtig",
	"Prickelnd",
	"Rau",
	"Reizend",
	"Respektvoll",
	"Romantisch",
	"Rot",
	"Ruhig",
	"Schäbig",
	"Schamlos",
	"Scharf",
	"Schillernd",
	"Schlammig",
	"Schlau",
	"Schmeichelnd",
	"Schmutzig",
	"Schrecklich",
	"Schüchtern",
	"Schwach",
	"Schwermütig",
	"Selbstsüchtig",
	"Spaßig",
	"Spießig",
	"Stolz",
	"Stur",
	"Talentiert",
	"Träumerisch",
	"Traurig",
	"Übermütig",
	"Ungeduldig",
	"Ungewöhnlich",
	"Unheimlich",
	"Unhöflich",
	"Unruhig",
	"Unscheinbar",
	"Unschuldig",
	"Unwohl",
	"Vergnügt",
	"Verlegen",
	"Verletzlich",
	"Verrückt",
	"Verschmust",
	"Verschmutzt",
	"Vertrauensvoll",
	"Verwirrt",
	"Vorsichtig",
	"Wagemutig",
	"Wahnsinnig",
	"Warm",
	"Weise",
	"Widerlich",
	"Wissbegierig",
	"Wundervoll",
	"Zart",
	"Zielstrebig",
	"Zornig",
	"Zufrieden",
	"Zurückhaltend",
	"Zuvorkommend",
}

var animalsDE = []string{
	"Adler",
	"Affe",
	"Albatros",
	"Alligator",
	"Alpaka",
	"Bär",
	"Biene",
	"Delfin",
	"Drachen",
	"Dschungelhuhn",
	"Eichhörnchen",
	"Elch",
	"Elefant",
	"Emu",
	"Ente",
	"Erdmännchen",
	"Esel",
	"Eule",
	"Falke",
	"Falke",
	"Fisch",
	"Fischotter",
	"Fledermaus",
	"Frettchen",
	"Fuchs",
	"Gecko",
	"Glückskäfer",
	"Gorilla",
	"Gottesanbeterin",
	"Hai",
	"Hamster",
	"Hornisse",
	"Huhn",
	"Hund",
	"Ibisse",
	"Leguan",
	"Impala",
	"Jaguar",
	"Kamel",
	"Känguru",
	"Kaninchen",
	"Katze",
	"Koala",
	"Königsrabe",
	"Kröte",
	"Kuh",
	"Lemur",
	"Leopard",
	"Lobster",
	"Mammut",
	"Maus",
	"Molch",
	"Mücke",
	"Nachtigall",
	"Narwal",
	"Okapi",
	"Opossum",
	"Panda",
	"Panther",
	"Pferd",
	"Pinguin",
	"Pony",
	"Qualle",
	"Rabe",
	"Saatkrähe",
	"Salamander",
	"Schaf",
	"Schildkröte",
	"Schmetterling",
	"Steinbock",
	"Tapir",
	"Tiger",
	"Viper",
	"Wal",
	"Waschbär",
	"Wespe",
	"Wiesel",
	"Wolf",
	"Zebra",
	"Ziege",
}

var suffixDE = map[string]string{
	"Adler":           "er",
	"Affe":            "er",
	"Albatros":        "er",
	"Alligator":       "er",
	"Alpaka":          "es",
	"Bär":             "er",
	"Biene":           "e",
	"Delfin":          "er",
	"Drachen":         "er",
	"Dschungelhuhn":   "es",
	"Eichhörnchen":    "es",
	"Elch":            "er",
	"Elefant":         "er",
	"Emu":             "er",
	"Ente":            "e",
	"Erdmännchen":     "es",
	"Esel":            "er",
	"Eule":            "e",
	"Falke":           "er",
	"Fisch":           "er",
	"Fischotter":      "er",
	"Fledermaus":      "e",
	"Frettchen":       "es",
	"Fuchs":           "er",
	"Gecko":           "er",
	"Glückskäfer":     "er",
	"Gorilla":         "er",
	"Gottesanbeterin": "e",
	"Hai":             "er",
	"Hamster":         "er",
	"Hornisse":        "e",
	"Huhn":            "es",
	"Hund":            "er",
	"Ibisse":          "e",
	"Leguan":          "er",
	"Impala":          "er",
	"Jaguar":          "er",
	"Kamel":           "es",
	"Känguru":         "es",
	"Kaninchen":       "es",
	"Katze":           "e",
	"Koala":           "er",
	"Königsrabe":      "e",
	"Kröte":           "e",
	"Kuh":             "e",
	"Lemur":           "er",
	"Leopard":         "er",
	"Lobster":         "er",
	"Mammut":          "er",
	"Maus":            "e",
	"Molch":           "er",
	"Mücke":           "e",
	"Nachtigall":      "e",
	"Narwal":          "er",
	"Okapi":           "es",
	"Opossum":         "es",
	"Panda":           "er",
	"Panther":         "er",
	"Pferd":           "es",
	"Pinguin":         "er",
	"Pony":            "es",
	"Qualle":          "e",
	"Rabe":            "er",
	"Saatkrähe":       "e",
	"Salamander":      "er",
	"Schaf":           "es",
	"Schildkröte":     "e",
	"Schmetterling":   "er",
	"Steinbock":       "er",
	"Tapir":           "er",
	"Tiger":           "er",
	"Viper":           "e",
	"Wal":             "er",
	"Waschbär":        "er",
	"Wespe":           "e",
	"Wiesel":          "es",
	"Wolf":            "er",
	"Zebra":           "es",
	"Ziege":           "e",
}

func GenNameDE() string {
	adj := adjectivesDE[rnd.Intn(len(adjectivesDE))]
	name := animalsDE[rnd.Intn(len(animalsDE))]
	suffix := suffixDE[name]

	// Remove male, female and neutral indicator
	adj = strings.TrimSuffix(adj, "er")
	adj = strings.TrimSuffix(adj, "e")
	adj = strings.TrimSuffix(adj, "es")

	return adj + suffix + name
}
